### ISSUE TITLE
Wallet Connect Spoofing Issue

### ISSUE THREAD

**Issue by CRYPTO-GENIK** [softwarecurator/sveltekit-siwe-example#1]
If you click connect and use [impersonator](https://www.impersonator.xyz/) you can log in as any wallet address by ignoring the sign and just refreshing the page.

<img width="338" alt="image" src="https://github.com/softwarecurator/sveltekit-siwe-example/assets/70092290/1f554f7b-7fc0-4928-89d0-d81fcb67a22f">

Update* 
Also rejecting the sign and then refreshing the page also exhibits the same behavior, you are signed in even without a sign.

**Comment by softwarecurator** [comment]
eip-login and this example is deprecated and no longer maintain use [svelte-wagmi](https://www.npmjs.com/package/svelte-wagmi)

**Comment by CRYPTO-GENIK** [comment]
I'm not trying to re-open this conversation but, is SIWE a feature in svelte-wagmi?
This answer could be useful for people Googling like me.
